dust3r_config:
  freeze: "encoder"
  pretrained_model_name_or_path: "checkpoints/pretrained_models/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth"

point_transformer_config:
  cross_dust: true
  cross_lseg: true
  cross_multi_scale: true
  enc_depths: [1, 1, 1, 3, 1]
  enc_channels: [32, 64, 128, 256, 512]
  enc_num_head: [2, 4, 8, 16, 32]
  enc_patch_size: [1024, 1024, 1024, 1024, 1024]
  dec_depths: [1, 1, 1, 1]
  dec_channels: [64, 64, 128, 256]
  dec_num_head: [4, 4, 8, 16]
  dec_patch_size: [1024, 1024, 1024, 1024]

gaussian_head_config: 
  rgb_residual: true
  feat_residual: false
  d_gs_feats: 64

lseg_config:
  pretrained_model_name_or_path: "checkpoints/pretrained_models/demo_e200.ckpt"
  half_res: true

freeze_dust3r: false
freeze_lseg: true